package com.noelevans555.logo3d;

/**
 * Demonstration programs which can be run with the Logo3d compiler.
 *
 * @author Noel Evans (noelevans555@gmail.com)
 */
final class DemoPrograms {

    static final String GRID_SPHERE = String.join("\n",
            " ; reverse to starting position on sphere surface            ",
            " penup                                                       ",
            " reverse 110                                                 ",
            " pendown                                                     ",
            "                                                             ",
            " ; turn so that forward movement is 'on' the sphere surface  ",
            " turnup 90                                                   ",
            "                                                             ",
            " ; repeat for 20 randomly selected colors                    ",
            " repeat 20 [                                                 ",
            "                                                             ",
            "     ; randomly select a color                               ",
            "     setcolor pick [                                         ",
            "         red green blue yellow                               ",
            "         cyan magenta orange purple                          ",
            "     ]                                                       ",
            "                                                             ",
            "     ; draw 500 lines on sphere surface in selected color    ",
            "     repeat 500 [                                            ",
            "                                                             ",
            "         ; draw forward line                                 ",
            "         forward 10                                          ",
            "                                                             ",
            "         ; turn down to track sphere surface. To stay on     ",
            "         ; the sphere surface, the next left/right turn must ",
            "         ; be performed halfway through this downward turn   ",
            "         turndown 2.5                                        ",
            "                                                             ",
            "         ; randomly turn left or right by 90 degrees         ",
            "         turnleft pick [ 90 270 ]                            ",
            "                                                             ",
            "         ; complete the downward turn                        ",
            "         turndown 2.5                                        ",
            "     ]                                                       ",
            " ]                                                           ");

    static final String SPIRAL_SHELL = String.join("\n",
            " ; define the starting step size and color                   ",
            " make step = 0.1                                             ",
            " make color = yellow                                         ",
            "                                                             ",
            " ; twist relative to the axis to make the visualization      ",
            " ; more interesting                                          ",
            " turnleft 50                                                 ",
            " turnup 50                                                   ",
            "                                                             ",
            " ; the shell is made from 50 'loops'                         ",
            " repeat 50 [                                                 ",
            "                                                             ",
            "     ; for each 'loop', draw a down-looping 'circle', with   ",
            "     ; ever-expanding radius and ever-changing color         ",
            "     repeat 360 [                                            ",
            "                                                             ",
            "         ; using the current color, move forward by the      ",
            "         ; current step size.                                ",
            "         setcolor color                                      ",
            "         forward step                                        ",
            "                                                             ",
            "         ; after each step, turn one degree down             ",
            "         turndown 1                                          ",
            "                                                             ",
            "         ; update the current step size and color before     ",
            "         ; taking the next step                              ",
            "         make step = step + 0.0001                           ",
            "         make color = color - [ 0 0.012 0]                   ",
            "     ]                                                       ",
            "                                                             ",
            "   ; twist left before starting the next loop                ",
            "   turnleft 10                                               ",
            " ]                                                           ");

    static final String RECURSIVE_TREE = String.join("\n",
            " ; define the recursive tree procedure with parameters:      ",
            " ;   size = length of the next 'branch'                      ",
            " ;   angle = tilt of the next 'branch'                       ",
            " ;   color = color of the next 'branch'                      ",
            " to tree size angle color [                                  ",
            "                                                             ",
            "     ; draw the branch in the specified color                ",
            "     setcolor color                                          ",
            "     forward size * 5                                        ",
            "                                                             ",
            "     ; dont draw next branch if size is small                ",
            "     if size < 0.8 [ stop ]                                  ",
            "                                                             ",
            "     ; pivot on forward axis and mark branching location     ",
            "     rollleft 90                                             ",
            "     mark local branch_point                                 ",
            "                                                             ",
            "     ; draw the left branch via recursive call               ",
            "     turnleft angle                                          ",
            "     tree size * 0.8 angle + 2 color + [ -10 20 10 ]         ",
            "                                                             ",
            "     ; return to the branching location                      ",
            "     goto branch_point                                       ",
            "                                                             ",
            "     ; draw the right branch via recursive call              ",
            "     turnright angle                                         ",
            "     tree size * 0.8 angle + 2 color + [ -10 20 10 ]         ",
            " ]                                                           ",
            "                                                             ",
            " ; reverse to the start position                             ",
            " penup                                                       ",
            " reverse 100                                                 ",
            " pendown                                                     ",
            "                                                             ",
            " ; run the procedure with starting values                    ",
            " tree 10 20 [130 50 0]                                       ");

    /**
     * Private constructor to prevent instantiation.
     */
    private DemoPrograms() {
    }

}
